name: Publish
on:
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Install SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
          source-url: https://nuget.pkg.github.com/zyofeng/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Restore packages
        run: dotnet restore
        working-directory: src
      - name: Build
        run: dotnet build -c Release --no-restore
        working-directory: src
      - name: Pack
        run: dotnet pack -c Release --no-build -o published
        working-directory: src
      - name: Push generated package to GitHub registry
        run: dotnet nuget push ./published/*.nupkg -k ${{secrets.GITHUB_TOKEN}}
        working-directory: src
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Nuget packages
          path: |
            src/published/*